### ISSUE TITLE
error: package `meteor-scss` is built for incompatible architecture

### ISSUE THREAD

**Issue by jadsonlourenco** [emlama/meteor-foundation5-sass#10]
I received this error when I'm working on Ubuntu, but it is a problem reported here: [https://github.com/fourseven/meteor-scss/issues/38](https://github.com/fourseven/meteor-scss/issues/38)

I resolved by updating the version of the dependency package. I now send a pull with this fix, here worked properly using version 0.9.6 of the "fourseven:scss" package.

Thank you.

**Comment by jadsonlourenco** [comment]
Thanks man!

**Comment by jadsonlourenco** [comment]
You send new release to Atmosphere with this fix? Because I see here the last release is 0.1.15, and on Atmosphere is 0.1.16, but not get from Atmosphere this version with this issue fixed. You plan to send new release soon?

Thank you!!

**Comment by emlama** [comment]
Hi @jadsonlourenco, you've been the best with helping on this package! I added you as a collaborator on this project and will look into adding you as a collaborator for the Atmosphere package too.

**Comment by jadsonlourenco** [comment]
Hi, thank you for the confidence, that's great. But I do not know how send updates for Atmosphere, haha. I'll learn how to do it.

**Comment by emlama** [comment]
This [document](https://meteor.hackpad.com/Unipackage-tvas8pXYMOW#:h=Administering-Packages) will give a great overview. What's your meteor username?

**Comment by jadsonlourenco** [comment]
jadsonlourenco

**Comment by emlama** [comment]
And you are added! Want to try and give it a push to Atmosphere?

**Comment by jadsonlourenco** [comment]
Not now, I'll create a test suite for that later, for now I do not want to break anything, then you can do this. Thanks, I'll study more about that later.
