### ISSUE TITLE
Installing Package

### ISSUE THREAD

**Issue by dcurletti** [emlama/meteor-foundation5-sass#14]
Hi there-  I'm having a bit of trouble installing/making the package run correctly.  It's showing up in my `/.meteor/packages` list but I don't see any files listed for it inside of the entire .meteor directory, especially this one: `.meteor/local/build/programs/server/assets/packages/` .  I also tried following the directions for installing it as a local package, but it seems that meteor retired the `link-package` command and so I wasn't able to get much further.  

None of the styles work, but the {{> kitchensink}} does populate the correct HTML code (without styling).

I was able to get the ewall version to run, but I would like to try this one out if possible.  

Thanks for any help.

**Comment by jadsonlourenco** [comment]
You are importing the SCSS correctly based on your style? 
Look: **@import ".meteor/local/build/programs/server/assets/packages/matthew_foundation5-sass/foundation";** add this on your SCSS/SASS file, and will work.

**Comment by dcurletti** [comment]
Thanks for the response, but when I place that line into my main.scss (the only sass file I currently have, I'm just starting the project) I get this error:

```
client/stylesheets/main.scss: Scss compiler error: undefined
Projects/Meteor/FoundationTest/client/stylesheets/main.scss:1: file to import not found or unreadable: ".meteor/local/build/programs/server/assets/packages/matthew_foundation5-sass/foundation"
```

**Comment by jadsonlourenco** [comment]
ok, try this, add the package:
`meteor add matthew:foundation5-sass`

Put this on your file **main.scss**:
`@import ".meteor/local/build/programs/server/assets/packages/matthew_foundation5-sass/foundation";`

Run these two commands separately, and tell me if you still receive this error.
`meteor update`
`meteor`

**Comment by dcurletti** [comment]
Awesome! Upgraded all of the following: 

```
This project is already at Meteor 1.0, the latest release.
  upgraded iron:location from version 1.0.0 to version 1.0.1
  upgraded raix:famono from version 0.9.15 to version 0.9.16
  upgraded iron:router from version 1.0.0 to version 1.0.1
  upgraded gadicohen:famous-views from version 0.1.23-test.1 to version 0.1.24
```

Not sure why it wasn't working before the update (it wasn't creating that link folder), but I'm glad it worked.  

Thanks for the help and time, now lets see how foundation plays with meteor+famous..

**Comment by jadsonlourenco** [comment]
great!
