### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by borchy37** [emlama/meteor-foundation5-sass#24]
I've tried to use it with Foundation 5.5.3. 
I get a compiler error: 

`.meteor/local/build/programs/server/assets/packages/matthew_foundation5-sass/scss/foundation/components/top-bar:80: argument `$color` of `scale-color($color, $red: false, $green: false, $blue: false, $hue: false, $saturation: false, $lightness: false, $alpha: false)` must be a color`

Any thoughts?

**Comment by juliancwirko** [comment]
@borchy37 hi, I think this is not maintained repo, try my package: https://atmospherejs.com/juliancwirko/zf5 this is Foundation 5.5.3 and it is ready for new Meteor 1.2 build plugin also it uses newest `fourseven:scss` package.

**Comment by borchy37** [comment]
@juliancwirko Yeah, was thinking about doing that. 
Tnx
