### ISSUE TITLE
Scss files don't get included

### ISSUE THREAD

**Issue by goette** [emlama/meteor-foundation5-sass#3]
When I run `meteor add matthew:foundation5-sass` it includes the entry to the packages file, but it doesn't seem to install anything, since this folder: .meteor/local/build/programs/server/assets/packages/matthew:foundation5-sass/

doesn't get created. Is there a way to fix it? I could also add this folder by hand, but I guess that defeats the purpose..

Thanks for any hints!

**Comment by juliancwirko** [comment]
@matthewforr I think there should be `{isAsset: true}` in package.js like here in zf5: https://github.com/juliancwirko/meteor-zf5/blob/master/package.js

**Comment by chuangbo** [comment]
I think #1 would fix this.

@matthewforr Could you dump a version to atmosphere please?

**Comment by emlama** [comment]
Thanks everyone for the help! I pushed this up to Atmosphere and tested with a fresh project and it appears to work just fine.
