### ISSUE TITLE
Compiled CSS?

### ISSUE THREAD

**Issue by jadsonlourenco** [emlama/meteor-foundation5-sass#6]
Hello, first I want to thank the initiative, Foundation really is a great framework, and with even better weather. 

I added this package but do not know if I need to add some tags have compiled CSS? Currently I get no style. Need run grunt to compile SCSS ou of meteor?

Thanks.

**Comment by emlama** [comment]
If you add a `.scss` file to your project and [import the Foundation files](https://github.com/matthewforr/meteor-foundation5-sass#add-the-scss-file), you should be good to go.

**Comment by jadsonlourenco** [comment]
I'm sorry, I was trying to use SCSS files within a "package". 

The solution was: I created a file "app.scss" and imported everything into it, in the application folder, then works. Thanks!
