### ISSUE TITLE
Correction of read me: The path should not contain a ':'

### ISSUE THREAD

**Issue by Nomeasmo** [emlama/meteor-foundation5-sass#8]
The path should not contain a colon and must be corrected to:
matthew_foundation5-sass using an underscore.

**Comment by jadsonlourenco** [comment]
I send a pull with this fixed, waiting to merge...

**Comment by emlama** [comment]
Awesome, thanks for catching this. Is this a change from 0.9.3?

**Comment by Nomeasmo** [comment]
Yes I'm on 0.9.3.

**Comment by jadsonlourenco** [comment]
this issue is fixed, not?

**Comment by Nomeasmo** [comment]
The issue was corrected by correcting the read me file. From my perspective it can be closed. It's working with the path now on 0.9.4
